# Generated by Django 3.0.2 on 2020-02-16 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0004_auto_20200215_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(default='{}')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='model.Model')),
            ],
            options={
                'db_table': 'puzzle_block',
            },
        ),
    ]
