# Generated by Django 3.0.2 on 2020-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0003_entry_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
