# Generated by Django 3.0.2 on 2020-02-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0005_auto_20200215_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='path',
            field=models.CharField(blank=True, default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
