# Generated by Django 3.0.2 on 2020-02-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0007_auto_20200215_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
