# Generated by Django 3.0.2 on 2020-02-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0008_entry_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='data',
            new_name='_data',
        ),
    ]
