# Generated by Django 3.0.2 on 2020-01-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
