# Generated by Django 3.0.2 on 2020-01-17 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
        ('website', '0003_website_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='home_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.Page'),
        ),
    ]
