# Generated by Django 3.0.2 on 2020-02-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_page_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='data',
            new_name='_data',
        ),
    ]
