# Generated by Django 3.0.2 on 2020-02-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='data',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
