# Generated by Django 3.0.2 on 2020-02-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20200215_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='data',
            field=models.TextField(default='{}'),
        ),
    ]
