# Generated by Django 3.0.2 on 2020-02-18 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
        ('model', '0004_auto_20200215_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='block.Block')),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.Model')),
            ],
            options={
                'db_table': 'puzzle_model_block',
            },
        ),
    ]
