# Generated by Django 3.0.2 on 2020-06-03 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_auto_20200220_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
